language: java
jdk: oraclejdk8
env:
  global:
    - CODECOV_TOKEN="43949c6d-6ac5-4606-adf0-c54a4b62353c"
script: 
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install
after_success:
  - bash <(curl -s https://codecov.io/bash)