language: java
jdk: oraclejdk8
cache:
  directories:
    - "$HOME/.m2"
install:
  - curl -o $HOME/.m2/settings.xml
    https://raw.githubusercontent.com/joaoabrodrigues/reclameaqui-complains/master/src/main/resources/settings.xml?token=AL_Bzfx3ahjczL_5JQNLvB9Rt16HlXKMks5cfz-FwA%3D%3D
  - mvn dependency:go-offline
script:
  - mvn clean install
env:
  global:
    - CODECOV_TOKEN="43949c6d-6ac5-4606-adf0-c54a4b62353c"
script: 
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install
after_success:
  - bash <(curl -s https://codecov.io/bash)